project_id = "uaiwjxojbpeljzxcvgof"

[functions.generate-optimizations]
verify_jwt = true

[functions.wasabi-proxy]
verify_jwt = true

[functions.wasabi-get-url]
verify_jwt = true

[functions.track-resource-usage]
verify_jwt = false

[functions.admin_list_visible_users]
verify_jwt = true

[functions."regenerate-avatars"]
verify_jwt = false

[functions."manage-session"]
verify_jwt = true
