project_id = "uaiwjxojbpeljzxcvgof"

[functions.generate-optimizations]
verify_jwt = true

[functions.wasabi-proxy]
verify_jwt = false

[functions.wasabi-get-url]
verify_jwt = false

[functions.track-resource-usage]
verify_jwt = false
